# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-GDB
version:      2.01
version_from: lib/Devel/GDB.pm
installdirs:  site
requires:
    Test::More:                    0
    Thread::Semaphore:             0
    threads::shared:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
